var mapObjectType = { OpenStreetMap_Mapnik:'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
											OpenStreetMap_BlackAndWhite:'http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png',
											OpenStreetMap_DE:'http://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png',
											OpenStreetMap_France:'http://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png',
											OpenStreetMap_HOT:'http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png',
											OpenTopoMap:'http://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
											Thunderforest_OpenCycleMap:'http://{s}.tile.thunderforest.com/cycle/{z}/{x}/{y}.png',
											Thunderforest_Transport:'http://{s}.tile.thunderforest.com/transport/{z}/{x}/{y}.png',
											Thunderforest_TransportDark:'http://{s}.tile.thunderforest.com/transport-dark/{z}/{x}/{y}.png',
											Thunderforest_SpinalMap: 'http://{s}.tile.thunderforest.com/spinal-map/{z}/{x}/{y}.png',
											Thunderforest_Landscape: 'http://{s}.tile.thunderforest.com/landscape/{z}/{x}/{y}.png',
											Thunderforest_Outdoors:'http://{s}.tile.thunderforest.com/outdoors/{z}/{x}/{y}.png',
										  Thunderforest_Pioneer: 'http://{s}.tile.thunderforest.com/pioneer/{z}/{x}/{y}.png',
											OpenMapSurfer_Roads:'http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}',
											OpenMapSurfer_Grayscale:'http://korona.geog.uni-heidelberg.de/tiles/roadsg/x={x}&y={y}&z={z}',
											Hydda_Full:'http://{s}.tile.openstreetmap.se/hydda/full/{z}/{x}/{y}.png',
											Hydda_Base:'http://{s}.tile.openstreetmap.se/hydda/base/{z}/{x}/{y}.png',
											Stamen_TonerBackground:'http://stamen-tiles-{s}.a.ssl.fastly.net/toner-background/{z}/{x}/{y}.png',
											Stamen_TonerLite:'http://stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}.png',
											Stamen_Watercolor:'http://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png',
											Stamen_Terrain:'http://stamen-tiles-{s}.a.ssl.fastly.net/terrain/{z}/{x}/{y}.png',
											Stamen_TerrainBackground:'http://stamen-tiles-{s}.a.ssl.fastly.net/terrain-background/{z}/{x}/{y}.png',
											Esri_WorldStreetMap:'http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',
											Esri_DeLorme:'http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/DeLorme_World_Base_Map/MapServer/tile/{z}/{y}/{x}',
											Esri_WorldTopoMap:'http://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',
											Esri_WorldImagery:'http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
											Esri_WorldTerrain:'http://server.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer/tile/{z}/{y}/{x}',
											Esri_WorldShadedRelief:'http://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/{z}/{y}/{x}',
											Esri_WorldPhysical:'http://server.arcgisonline.com/ArcGIS/rest/services/World_Physical_Map/MapServer/tile/{z}/{y}/{x}',
											Esri_OceanBasema:'http://server.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/{z}/{y}/{x}',
											Esri_NatGeoWorldMap:'http://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}',
											Esri_WorldGrayCanvas:'http://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}',
											Game_Of_Thrones:'https://cartocdn-ashbu.global.ssl.fastly.net/ramirocartodb/api/v1/map/named/tpl_756aec63_3adb_48b6_9d14_331c6cbc47cf/all/{z}/{x}/{y}.png'
										};
